# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
# Import API key
from api_keys import weather_api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "cities.csv"

df = pd.read_csv(output_data_file)
df.head()

,Unnamed: 0,city,lat,lon,humidity,wind,clouds,country,date,temp
0,0,georgetown,5.41,100.34,94,3.36,20,MY,1595634640,77.00
1,1,hermanus,-34.42,19.23,47,1.99,0,ZA,1595634640,61.00
2,2,coahuayana,18.73,-103.68,83,17.22,90,MX,1595634640,77.00
3,3,cidreira,-30.18,-50.21,84,9.66,100,BR,1595634640,62.87
4,4,tuktoyaktuk,69.45,-133.04,55,4.70,75,CA,1595634640,62.60

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Google API Key
from api_keys import g_key
gmaps.configure(api_key=g_key)

In [4]:
# cities_pd["Lat"] = ""
# cities_pd["Lng"] = ""
# cities_pd["Airport Name"] = ""
# cities_pd["Airport Address"] = ""
# cities_pd["Airport Rating"] = ""
# cities_pd.head()

In [5]:
# Store latitude and longitude in locations
locations = df[["lat", "lon"]]
humidity = df["humidity"]

In [6]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=300,
                                 point_radius=5)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [8]:
df_weather = df.loc[(df["temp"]<70) &(df["clouds"] == 0)]
df_weather

,Unnamed: 0,city,lat,lon,humidity,wind,clouds,country,date,temp
1,1,hermanus,-34.42,19.23,47,1.99,0,ZA,1595634640,61.00
6,6,cape town,-33.93,18.42,66,5.82,0,ZA,1595634464,50.00
15,15,vila,42.03,-8.16,77,6.93,0,PT,1595634641,66.20
17,17,bredasdorp,-34.53,20.04,87,4.70,0,ZA,1595634642,46.40
31,31,castro,-24.79,-50.01,75,4.41,0,BR,1595634644,57.52
38,38,kasama,-10.21,31.18,90,3.36,0,ZM,1595634644,45.41
46,46,qaanaaq,77.48,-69.36,54,2.01,0,GL,1595634645,48.00
52,52,lagoa,39.05,-27.98,79,11.12,0,PT,1595634647,69.94
59,59,namibe,-15.20,12.15,83,4.14,0,AO,1595634648,65.71
65,65,vredendal,-31.67,18.50,27,14.58,0,ZA,1595634648,65.64
93,93,saldanha,-33.01,17.94,61,1.12,0,ZA,1595634652,50.00
96,96,richards bay,-28.78,32.04,78,9.04,0,ZA,1595634653,60.39
127,127,east london,-33.02,27.91,27,4.81,0,ZA,1595634657,64.87
131,131,port elizabeth,-33.92,25.57,53,3.36,0,ZA,1595634657,51.80
138,138,port alfred,-33.59,26.89,26,11.21,0,ZA,1595634658,67.17
148,148,longyearbyen,78.22,15.64,87,14.99,0,SJ,1595634660,51.80
165,165,cruzilia,-21.84,-44.81,65,4.79,0,BR,1595634662,56.93
174,174,karratha,-20.74,116.85,44,15.05,0,AU,1595634395,67.28
179,179,port hedland,-20.32,118.57,34,10.29,0,AU,1595634665,64.40
198,198,kruisfontein,-34.00,24.73,27,11.16,0,ZA,1595634667,61.27
199,199,sar-e pul,35.83,66.17,45,1.99,0,AF,1595634667,63.12
222,222,hovd,48.01,91.64,49,2.44,0,MN,1595634671,68.45
225,225,carnarvon,-24.87,113.63,81,8.05,0,AU,1595634671,50.00
232,232,waipawa,-41.41,175.52,62,5.82,0,NZ,1595634672,53.60
233,233,tilichiki,60.47,166.10,52,4.03,0,RU,1595634672,67.26
249,249,yeniseysk,58.45,92.17,90,2.37,0,RU,1595634675,54.45
250,250,safranbolu,41.25,32.69,78,2.26,0,TR,1595634675,59.88
265,265,peniche,39.36,-9.38,89,8.01,0,PT,1595634677,64.99
273,273,constitucion,-35.33,-72.42,72,4.45,0,CL,1595634678,46.96
295,295,zhezkazgan,47.80,67.71,48,8.95,0,KZ,1595634681,62.60
302,302,rundu,-17.93,19.77,46,4.70,0,NaN,1595634681,53.60
305,305,san quintin,30.48,-115.95,67,12.39,0,MX,1595634682,69.94
307,307,aleksandrov gay,50.15,48.57,57,7.45,0,RU,1595634682,64.17
323,323,nevsehir,38.92,34.67,56,8.05,0,TR,1595634684,68.00
373,373,geraldton,-28.77,114.60,66,19.46,0,AU,1595634691,48.20
408,408,kokstad,-30.55,29.42,53,4.52,0,ZA,1595634695,44.11
420,420,la cumbre,-30.98,-64.49,49,1.01,0,AR,1595634697,39.00
422,422,calvinia,-31.47,19.78,39,8.41,0,ZA,1595634697,54.28
430,430,port lincoln,-34.73,135.87,81,2.15,0,AU,1595634698,54.43
432,432,luderitz,-26.65,15.16,22,8.05,0,NaN,1595634698,69.80
447,447,iskateley,67.68,53.15,70,9.73,0,RU,1595634700,57.92
460,460,morondava,-20.28,44.28,55,13.67,0,MG,1595634702,68.61
468,468,taltal,-25.40,-70.48,59,2.91,0,CL,1595634703,53.46
471,471,kenitra,34.26,-6.58,88,4.70,0,MA,1595634462,69.80
493,493,opuwo,-18.06,13.84,40,8.43,0,NaN,1595634706,54.05
508,508,horta,38.53,-28.63,74,7.49,0,PT,1595634489,69.60
517,517,angatuba,-23.49,-48.41,53,2.89,0,BR,1595634709,63.52
520,520,sokol,59.46,40.12,94,2.80,0,RU,1595634709,47.37
523,523,caluquembe,-13.78,14.68,64,2.08,0,AO,1595634710,48.97
524,524,ust-ilimsk,58.00,102.66,63,5.66,0,RU,1595634710,56.66
529,529,henties bay,-22.12,14.28,19,1.99,0,NaN,1595634710,66.00
532,532,saint-francois,46.42,3.91,72,3.36,0,FR,1595634711,59.00

In [10]:
df_weather.dropna()

,Unnamed: 0,city,lat,lon,humidity,wind,clouds,country,date,temp
1,1,hermanus,-34.42,19.23,47,1.99,0,ZA,1595634640,61.00
6,6,cape town,-33.93,18.42,66,5.82,0,ZA,1595634464,50.00
15,15,vila,42.03,-8.16,77,6.93,0,PT,1595634641,66.20
17,17,bredasdorp,-34.53,20.04,87,4.70,0,ZA,1595634642,46.40
31,31,castro,-24.79,-50.01,75,4.41,0,BR,1595634644,57.52
38,38,kasama,-10.21,31.18,90,3.36,0,ZM,1595634644,45.41
46,46,qaanaaq,77.48,-69.36,54,2.01,0,GL,1595634645,48.00
52,52,lagoa,39.05,-27.98,79,11.12,0,PT,1595634647,69.94
59,59,namibe,-15.20,12.15,83,4.14,0,AO,1595634648,65.71
65,65,vredendal,-31.67,18.50,27,14.58,0,ZA,1595634648,65.64
93,93,saldanha,-33.01,17.94,61,1.12,0,ZA,1595634652,50.00
96,96,richards bay,-28.78,32.04,78,9.04,0,ZA,1595634653,60.39
127,127,east london,-33.02,27.91,27,4.81,0,ZA,1595634657,64.87
131,131,port elizabeth,-33.92,25.57,53,3.36,0,ZA,1595634657,51.80
138,138,port alfred,-33.59,26.89,26,11.21,0,ZA,1595634658,67.17
148,148,longyearbyen,78.22,15.64,87,14.99,0,SJ,1595634660,51.80
165,165,cruzilia,-21.84,-44.81,65,4.79,0,BR,1595634662,56.93
174,174,karratha,-20.74,116.85,44,15.05,0,AU,1595634395,67.28
179,179,port hedland,-20.32,118.57,34,10.29,0,AU,1595634665,64.40
198,198,kruisfontein,-34.00,24.73,27,11.16,0,ZA,1595634667,61.27
199,199,sar-e pul,35.83,66.17,45,1.99,0,AF,1595634667,63.12
222,222,hovd,48.01,91.64,49,2.44,0,MN,1595634671,68.45
225,225,carnarvon,-24.87,113.63,81,8.05,0,AU,1595634671,50.00
232,232,waipawa,-41.41,175.52,62,5.82,0,NZ,1595634672,53.60
233,233,tilichiki,60.47,166.10,52,4.03,0,RU,1595634672,67.26
249,249,yeniseysk,58.45,92.17,90,2.37,0,RU,1595634675,54.45
250,250,safranbolu,41.25,32.69,78,2.26,0,TR,1595634675,59.88
265,265,peniche,39.36,-9.38,89,8.01,0,PT,1595634677,64.99
273,273,constitucion,-35.33,-72.42,72,4.45,0,CL,1595634678,46.96
295,295,zhezkazgan,47.80,67.71,48,8.95,0,KZ,1595634681,62.60
305,305,san quintin,30.48,-115.95,67,12.39,0,MX,1595634682,69.94
307,307,aleksandrov gay,50.15,48.57,57,7.45,0,RU,1595634682,64.17
323,323,nevsehir,38.92,34.67,56,8.05,0,TR,1595634684,68.00
373,373,geraldton,-28.77,114.60,66,19.46,0,AU,1595634691,48.20
408,408,kokstad,-30.55,29.42,53,4.52,0,ZA,1595634695,44.11
420,420,la cumbre,-30.98,-64.49,49,1.01,0,AR,1595634697,39.00
422,422,calvinia,-31.47,19.78,39,8.41,0,ZA,1595634697,54.28
430,430,port lincoln,-34.73,135.87,81,2.15,0,AU,1595634698,54.43
447,447,iskateley,67.68,53.15,70,9.73,0,RU,1595634700,57.92
460,460,morondava,-20.28,44.28,55,13.67,0,MG,1595634702,68.61
468,468,taltal,-25.40,-70.48,59,2.91,0,CL,1595634703,53.46
471,471,kenitra,34.26,-6.58,88,4.70,0,MA,1595634462,69.80
508,508,horta,38.53,-28.63,74,7.49,0,PT,1595634489,69.60
517,517,angatuba,-23.49,-48.41,53,2.89,0,BR,1595634709,63.52
520,520,sokol,59.46,40.12,94,2.80,0,RU,1595634709,47.37
523,523,caluquembe,-13.78,14.68,64,2.08,0,AO,1595634710,48.97
524,524,ust-ilimsk,58.00,102.66,63,5.66,0,RU,1595634710,56.66
532,532,saint-francois,46.42,3.91,72,3.36,0,FR,1595634711,59.00

       lat     lon
0     5.41  100.34
1   -34.42   19.23
2    18.73 -103.68
3   -30.18  -50.21
4    69.45 -133.04
..     ...     ...
576  41.12   80.26
577  55.30   53.19
578  28.33  -82.68
579  50.50 -120.80
580   2.79   24.73

[581 rows x 2 columns]

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [14]:
hotel_df = df_weather[["city", "country", "lat", "lon"]].copy()
hotel_df["hotel name"] = ""
hotel_df

                city country    lat     lon hotel name
1           hermanus      ZA -34.42   19.23
6          cape town      ZA -33.93   18.42
15              vila      PT  42.03   -8.16
17        bredasdorp      ZA -34.53   20.04
31            castro      BR -24.79  -50.01
38            kasama      ZM -10.21   31.18
46           qaanaaq      GL  77.48  -69.36
52             lagoa      PT  39.05  -27.98
59            namibe      AO -15.20   12.15
65         vredendal      ZA -31.67   18.50
93          saldanha      ZA -33.01   17.94
96      richards bay      ZA -28.78   32.04
127      east london      ZA -33.02   27.91
131   port elizabeth      ZA -33.92   25.57
138      port alfred      ZA -33.59   26.89
148     longyearbyen      SJ  78.22   15.64
165         cruzilia      BR -21.84  -44.81
174         karratha      AU -20.74  116.85
179     port hedland      AU -20.32  118.57
198     kruisfontein      ZA -34.00   24.73
199        sar-e pul      AF  35.83   66.17
222             hovd      MN  48.01   91.64
225        carnarvon      AU -24.87  113.63
232          waipawa      NZ -41.41  175.52
233        tilichiki      RU  60.47  166.10
249        yeniseysk      RU  58.45   92.17
250       safranbolu      TR  41.25   32.69
265          peniche      PT  39.36   -9.38
273     constitucion      CL -35.33  -72.42
295       zhezkazgan      KZ  47.80   67.71
302            rundu     NaN -17.93   19.77
305      san quintin      MX  30.48 -115.95
307  aleksandrov gay      RU  50.15   48.57
323         nevsehir      TR  38.92   34.67
373        geraldton      AU -28.77  114.60
408          kokstad      ZA -30.55   29.42
420        la cumbre      AR -30.98  -64.49
422         calvinia      ZA -31.47   19.78
430     port lincoln      AU -34.73  135.87
432         luderitz     NaN -26.65   15.16
447        iskateley      RU  67.68   53.15
460        morondava      MG -20.28   44.28
468           taltal      CL -25.40  -70.48
471          kenitra      MA  34.26   -6.58
493            opuwo     NaN -18.06   13.84
508            horta      PT  38.53  -28.63
517         angatuba      BR -23.49  -48.41
520            sokol      RU  59.46   40.12
523       caluquembe      AO -13.78   14.68
524       ust-ilimsk      RU  58.00  102.66
529      henties bay     NaN -22.12   14.28
532   saint-francois      FR  46.42    3.91

In [16]:
# create a params dict that will be updated with new city each iteration
params = {"key": g_key, "types":"lodging","radius": 5000}

# Loop through the cities_pd and run a lat/long search for each city
for index, row in hotel_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    latitude = row['lat']
    longitude = row['lon']

    # update address key value
    params['location'] = f"{latitude},{longitude}"

    # make request
    hotel_address = requests.get(base_url, params=params).json()
    
    # print the cities_lat_lng url, avoid doing for public github repos in order to avoid exposing key
    # print(cities_lat_lng.url)
    
    try:
        
        hotel_df.loc[index, "hotel name"] = hotel_address["results"][0]["name"]
    except:
        print("missing name")
    

# Visualize to confirm lat lng appear
hotel_df.head()

missing name
missing name
missing name
missing name
missing name

          city country    lat    lon                         hotel name
1     hermanus      ZA -34.42  19.23         Misty Waves Boutique Hotel
6    cape town      ZA -33.93  18.42  Southern Sun Waterfront Cape Town
15        vila      PT  42.03  -8.16               Hotel Castrum Villae
17  bredasdorp      ZA -34.53  20.04           Bredasdorp Country Manor
31      castro      BR -24.79 -50.01                     CHACARA BAILLY

In [20]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{hotel name}</dd>
<dt>City</dt><dd>{city}</dd>
<dt>Country</dt><dd>{country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["lat", "lon"]]

In [21]:
# Add marker layer ontop of heat map
layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# Display figure
fig.add_layer(layer)
fig

Figure(layout=FigureLayout(height='420px'))